# Site title
title: Purdue Statistics Graduate Student Organization

# Tagline below the site title on post list pages
tagline: Student Seminars

# A description of your site for social meta tag, search engines, and feed.xml
description:

# The base hostname & protocol of your site for where absolute urls are needed
url: "https://gso-stat.github.io"

# The subpath of your site, e.g. /blog, for generating urls
baseurl: ""

# The site cover image on the home page
image: /images/stat_logo.jpg

# The shortname for your Disqus site to enable comments
disqus_shortname:

# Your Google Analytics tracking code
google_analytics_tracking_id:


# Site navigation
nav:
  - title: "Home"
    url:   "/"
  - title: "About"
    url:   "http://www.stat.purdue.edu/student_organizations/gso/index.php"


# The links in the site footer
footer_links:
  - title: "Department of Statistics, Purdue University"
    url:   "http://www.stat.purdue.edu/"


# Author information
authors:
  yixuan:
    name: Yixuan Qiu
    website: http://statr.me/
    bio: Ph.D. Candidate, Purdue University
    avatar: /images/avatar_yixuan.png
  mohit:
    name: Mohit Dayal
    website: http://mohitdayal.strikingly.com/
    bio: Ph.D. Student, Purdue University
  ryan:
    name: Ryan Murphy
    bio: Ph.D. Student, Purdue University
  patrick:
    name: Patrick Medina
    bio: Ph.D. Candidate, Purdue University
  xiaosu:
    name: Xiaosu Tong
    bio: Ph.D. Candidate, Purdue University
  will:
    name: Will Eagan
    bio: Ph.D. Candidate, Purdue University
  jiasen:
    name: Jiasen Yang
    bio: Ph.D. Candidate, Purdue University
  barret:
    name: Barret Schloerke
    bio: Ph.D. Candidate, Purdue University


# Extra Open Graph and Twitter Cards settings for social sharing

# Fallback og:image when no page.image or site.image. Facebook requires image be
# at least 200 x 200 pixels.
og_image:

# twitter:site. Your Twitter username without "@"
twitter_site:


# http://jekyllrb.com/docs/pagination/
paginate: 5
paginate_path: page/:num/
gems: [jekyll-paginate]

permalink: /:title/
markdown: kramdown
kramdown:
  input: GFM
